//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductBoard()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> DivisonID { get; set; }
        public Nullable<int> PriceIndexID { get; set; }
        public Nullable<int> ColorCodeID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string StockStat { get; set; }
        public string Description { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<int> VendorID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Division Division { get; set; }
        public virtual PriceIndex PriceIndex { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
    }
}
